twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
            locale: "%locale%"
            envTest: "%envTest%"
            link_site: "%link_site%"
            link_site_short: "%link_site_short%"
            link_landing: "%link_landing%"
            mail_contact: "%mail_contact%"
            tel_contact: "%tel_contact%"
            name_repo: "%name_repo%"
            name_site: "%name_site%"
            societe: "%societe%"
            societe_street: "%societe_street%"
            societe_cp: "%societe_cp%"
            societe_country: "%societe_country%"
            societe_city: "%societe_city%"
            siren: "%siren%"
            facebook: "%facebook%"
            github: "%github%"
            linkedin: "%linkedin%"
            nameSiteConfig: "%nameSiteConfig%"

when@test:
    twig:
        strict_variables: true
